name: OriginCore
version: '${project.version}'
main: cn.originmc.plugins.origincore.OriginCore
api-version: 1.13
authors: [ Yeqi ]
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - PlayerPoints
  - Vault
  - LuckPerms
  - MMOItems
  - ItemsAdder
  - MythicLib
  - MythicMobs